Project: Associations
verissimohenry/Private-Events pull request #1
Opened 2021-05-19 13:13 UTC by verissimohenry

In this project, I build an application named Private Events and that behaves similarly to Eventbrite. The main goal was to put in practice the main concepts of Associations in rails.

2021-05-19 19:30 UTC, NtwaliHeritier requested changes
### **STATUS: INVALID❌❌❌❌**

Hello @verissimohenry 
Great work submitting this project.
I can tell you put in a lot of work, however, It was invalidated due to the following reason.

When I run the project locally, I get the error below. Kindly fix it and ask for another review👍

![Capture](https://user-images.githubusercontent.com/61793815/118872952-7123e280-b8e9-11eb-82df-4b93ae76b497.PNG)

Happy coding💻💻💻

2021-05-20 11:44 UTC, george-shammar requested changes
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

This is impressive. :+1: :clap: 

**Highlights:**
- Your models and associations are set up correctly. :+1: 
- Credit for extra step you took to make your user interface neat.

However, you need to make some changes in order to get the project approved.

- [x] The event's show page should display the list of attendants. I created an event and invited two users but the event show page is not displaying any of them.
- [x] User should be able to retrieve future events the user has created as well as past events the user has created. Currently, both are lumped together in the user's show page.
- [x] Your project has no README. Please include one.
- [x] Include validation and association tests for your models. You currently have none.
- [x] Authentication and event management features too should have integration tests. Make use of Capybara.
- [x] Remove commented codes from your repo. It is not professional. e.g Invites_controller.rb and everywhere else you have commented codes.

[OPTIONAL]

- [x] Specify routes only for used actions. e.g You have ` resources :invites` whereas you did not make use of all the controller actions.

Effect these changes and submit another CRR when you're ready.

If you require clarification, drop your message here and ping me on slack.

Cheers and happy coding. :+1: :smile:

2021-05-21 19:59 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ♻️
Hey @verissimohenry, Weldone for mplementing this changes:
####Highlited
- [ ] The event's show page should display the list of attendants. I created an event and invited two users but the event show page is not displaying any of them.
- [ ]  User should be able to retrieve future events the user has created as well as past events the user has created. 

However this changes are still required to get youer project approved:
#####Improve
- [ ] Your project has no README. Please include one.
- [ ]  Include validation and association tests for your models. You currently have none.
- [ ]  Authentication and event management features too should have integration tests.
- [ ]  Remove commented codes from your repo. 
Once Done kindly requested for another review

2021-05-22 11:32 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, thank you for working on changes suggested by previous reviewers :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git Flow.
- [x] PR is descriptive.
## To Improve 🙏
- [x] Please add a README file. KIndly see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) and this [lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) from Pathwright.
- [x] Kindly remove commented code from invites controller. It makes code unclean.
### User's show action:
- [x] It should list events created by user, i.e. @created_events = current_user.events. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png).
 - [x] It should display events that the user is attending to separated in the past and upcoming.
- [x] It should list events previously attended by user using event model scope, i.e. @past_events = current_user.attended_events.previous. Please see this screenshot.
- [x] It should list upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png).
- [x] The event's show page should display the list of attendees.
- [x] I am unable to invite a user to attend an event I have created.
- [x] Please add unit tests for validations and associations of models using Rspec.
- [ ] Please add integration tests for authentication using Rspec + Capybara.
- [ ] Please add integration tests for event management features using Rspec + Capybara.
- [ ]  Please make sure that you have worked on all the changes suggested and your project is ready for a review before asking for another code review.

# Optional
- [ ] Please protect routes by configuring only those routes which are being used  i.e. resources :events, only: [:new, :create, :show, :index]

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-05-22 14:16 UTC, mke2111 commented
## Project is under review. Please be patient

2021-05-22 14:34 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The app runs just fine and a user can be invited successfully.
    2. The readme file is now clear and concise

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] I'm unable to log in with an existing username. A pop-up of **Invalid name** is shown. Give this a fix.
- [ ] You currently have 3 unit tests. Add more unit(validation and association) and integration(feature, requests) tests. You may choose to use Shoulda, CapyBara, Rspec gems.
- [ ] You have numerous pieces of commented-out code in your files. (invites controller) Clean up your repo.


#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-05-22 14:36 UTC, mke2111 commented on app/controllers/invites_controller.rb
> +  #   @invite.update(discription: false)
Clean up this file

2021-05-22 14:38 UTC, mke2111 commented on README.md
> +$ rspec spec/models/invite_spec.rb
Add tests in all these files.

2021-05-22 14:39 UTC, mke2111 commented on README.md
> +$ rspec spec/models/event_spec.rb
OPTIONAL

- [ ] You may choose to run `rspec` to run all the test files in the spec directory

2021-05-22 17:20 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- It has functional login page :+1: 
- Logged in user can create new event :100: 
- Navigation links are present at the top of the page :1st_place_medal: 
- Event's index page displays past and upcoming events lists :+1: 
- The event's show page displays the list of attendants :100: 
- The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming :1st_place_medal: 

To improve :factory_worker: [REQUIRED]:

- [ ] Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.
- [ ] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] authentication have has integration tests (Rspec + Capybara) ( [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ]  event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

Nice to have:

- [ ] routes only for used actions, i.e. resources :events, only: [:new, :create, :show, :index]
- [ ]

2021-05-22 17:20 UTC, rindrajosia commented on app/controllers/invites_controller.rb
> +  # end
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-22 19:14 UTC, UmairArshadDev approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**Hi @verissimohenry  It is the 7th review, but there are still issues with testing. I will go ahead and mark this as complete.**
- You can now merge to master after completing the unit and integration testing and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-05-25 07:44 UTC, merged